REGION_CONFIG = {
    "4_4_ADJACENCY1": [['intersection_2_2', 'intersection_1_1', 'intersection_2_1', 'intersection_3_1', 'dummy'],
                       ['intersection_1_4', 'dummy', 'intersection_1_3', 'intersection_2_3', 'intersection_1_2'],
                       ['intersection_4_3', 'intersection_3_2', 'intersection_4_2', 'dummy', 'intersection_4_1'],
                       ['dummy', 'intersection_2_4', 'intersection_3_4', 'intersection_4_4', 'intersection_3_3']],
    "4_4_ADJACENCY2": [['intersection_1_3', 'dummy', 'intersection_1_2', 'intersection_2_2', 'intersection_1_1'],
                       ['intersection_3_2', 'intersection_2_1', 'intersection_3_1', 'intersection_4_1', 'dummy'],

                       ['dummy', 'intersection_1_4', 'intersection_2_4', 'intersection_3_4', 'intersection_2_3'],
                       ['intersection_4_4', 'intersection_3_3', 'intersection_4_3', 'dummy', 'intersection_4_2']],
    "4_4_GRID": [['dummy', 'intersection_1_4', 'intersection_2_4',
                  'dummy', 'intersection_1_3', 'intersection_2_3'],
                 ['dummy', 'intersection_1_2', 'intersection_2_2',
                  'dummy', 'intersection_1_1', 'intersection_2_1'],
                 ['intersection_3_4', 'intersection_4_4', 'dummy',
                  'intersection_3_3', 'intersection_4_3', 'dummy'],
                 ['intersection_3_2', 'intersection_4_2', 'dummy',
                  'intersection_3_1', 'intersection_4_1', 'dummy']],
    "16_3_ADJACENCY1": [['intersection_2_2', 'intersection_1_1', 'intersection_2_1', 'intersection_3_1', 'dummy'],
                       ['intersection_1_4', 'dummy', 'intersection_1_3', 'intersection_2_3', 'intersection_1_2'],
                       ['intersection_3_4', 'dummy', 'intersection_3_3', 'dummy', 'intersection_3_2'],
                       ['dummy', 'intersection_1_5', 'intersection_2_5', 'intersection_3_5', 'intersection_2_4'],
                       ['intersection_2_7', 'intersection_1_6', 'intersection_2_6', 'intersection_3_6', 'dummy'],
                       ['intersection_1_9', 'dummy', 'intersection_1_8', 'intersection_2_8', 'intersection_1_7'],
                       ['intersection_3_9', 'dummy', 'intersection_3_8', 'dummy', 'intersection_3_7'],
                       ['dummy', 'intersection_1_10', 'intersection_2_10', 'intersection_3_10', 'intersection_2_9'],
                       ['intersection_2_12', 'intersection_1_11', 'intersection_2_11', 'intersection_3_11', 'dummy'],
                       ['intersection_1_14', 'dummy', 'intersection_1_13', 'intersection_2_13', 'intersection_1_12'],
                       ['intersection_3_14', 'dummy', 'intersection_3_13', 'dummy', 'intersection_3_12'],
                       ['dummy', 'intersection_1_15', 'intersection_2_15', 'intersection_3_15', 'intersection_2_14'],
                       ['dummy', 'intersection_1_16', 'intersection_2_16', 'intersection_3_16', 'dummy'], ],
    "16_3_ADJACENCY2": [['dummy', 'intersection_1_5', 'intersection_2_5', 'intersection_3_5', 'intersection_2_4'],
                        ['intersection_3_4', 'intersection_2_3', 'intersection_3_3', 'dummy', 'intersection_3_2'],
                        ['intersection_3_14', 'intersection_2_13', 'intersection_3_13', 'dummy', 'intersection_3_12'],
                        ['intersection_2_12', 'intersection_1_11', 'intersection_2_11', 'intersection_3_11', 'dummy'],
                        ['intersection_2_2', 'intersection_1_1', 'intersection_2_1', 'intersection_3_1', 'dummy'],
                        ['dummy', 'intersection_1_16', 'intersection_2_16', 'intersection_3_16', 'dummy'],
                        ['dummy', 'intersection_1_15', 'intersection_2_15', 'intersection_3_15', 'intersection_2_14'],
                        ['intersection_1_9', 'dummy', 'intersection_1_8', 'intersection_2_8', 'intersection_1_7'],
                        ['dummy', 'intersection_1_10', 'intersection_2_10', 'intersection_3_10', 'intersection_2_9'],
                        ['intersection_1_14', 'dummy', 'intersection_1_13', 'dummy', 'intersection_1_12'],
                        ['intersection_3_9', 'dummy', 'intersection_3_8', 'dummy', 'intersection_3_7'],
                        ['intersection_2_7', 'intersection_1_6', 'intersection_2_6', 'intersection_3_6', 'dummy'],
                        ['intersection_1_4', 'dummy', 'intersection_1_3', 'dummy', 'intersection_1_2']],
    "16_3_ADJACENCY3": [['intersection_3_9', 'intersection_2_8', 'intersection_3_8', 'dummy', 'intersection_3_7'],
                        ['dummy', 'intersection_1_10', 'intersection_2_10', 'intersection_3_10', 'intersection_2_9'],
                        ['intersection_1_9', 'dummy', 'intersection_1_8', 'dummy', 'intersection_1_7'],
                        ['intersection_2_7', 'intersection_1_6', 'intersection_2_6', 'intersection_3_6', 'dummy'],
                        ['intersection_1_4', 'dummy', 'intersection_1_3', 'intersection_2_3', 'intersection_1_2'],
                        ['intersection_2_2', 'intersection_1_1', 'intersection_2_1', 'intersection_3_1', 'dummy'],
                        ['dummy', 'intersection_1_5', 'intersection_2_5', 'intersection_3_5', 'intersection_2_4'],
                        ['intersection_1_14', 'dummy', 'intersection_1_13', 'intersection_2_13', 'intersection_1_12'],
                        ['dummy', 'intersection_1_16', 'intersection_2_16', 'intersection_3_16', 'dummy'],
                        ['intersection_3_14', 'dummy', 'intersection_3_13', 'dummy', 'intersection_3_12'],
                        ['intersection_2_12', 'intersection_1_11', 'intersection_2_11', 'intersection_3_11', 'dummy'],
                        ['intersection_3_4', 'dummy', 'intersection_3_3', 'dummy', 'intersection_3_2'],
                        ['dummy', 'intersection_1_15', 'intersection_2_15', 'intersection_3_15', 'intersection_2_14']],
    "16_3_ADJACENCY4": [['intersection_2_2', 'intersection_1_1', 'intersection_2_1', 'intersection_3_1', 'dummy'],
                        ['intersection_1_4', 'dummy', 'intersection_1_3', 'intersection_2_3', 'intersection_1_2'],
                        ['intersection_3_4', 'dummy', 'intersection_3_3', 'dummy', 'intersection_3_2'],
                        ['dummy', 'intersection_1_16', 'intersection_2_16', 'intersection_3_16', 'dummy'],
                        ['intersection_1_9', 'dummy', 'intersection_1_8', 'intersection_2_8', 'intersection_1_7'],
                        ['dummy', 'intersection_1_15', 'intersection_2_15', 'intersection_3_15', 'intersection_2_14'],
                        ['dummy', 'intersection_1_5', 'intersection_2_5', 'intersection_3_5', 'intersection_2_4'],
                        ['dummy', 'intersection_1_10', 'intersection_2_10', 'intersection_3_10', 'intersection_2_9'],
                        ['intersection_2_7', 'intersection_1_6', 'intersection_2_6', 'intersection_3_6', 'dummy'],
                        ['intersection_2_12', 'intersection_1_11', 'intersection_2_11', 'intersection_3_11', 'dummy'],
                        ['intersection_3_14', 'intersection_2_13', 'intersection_3_13', 'dummy', 'intersection_3_12'],
                        ['intersection_1_14', 'dummy', 'intersection_1_13', 'dummy', 'intersection_1_12'],
                        ['intersection_3_9', 'dummy', 'intersection_3_8', 'dummy', 'intersection_3_7']],
    "16_3_ADJACENCY5": [['intersection_1_4', 'dummy', 'intersection_1_3', 'intersection_2_3', 'intersection_1_2'],
                        ['intersection_1_9', 'dummy', 'intersection_1_8', 'intersection_2_8', 'intersection_1_7'],
                        ['dummy', 'intersection_1_15', 'intersection_2_15', 'intersection_3_15', 'intersection_2_14'],
                        ['dummy', 'intersection_1_10', 'intersection_2_10', 'intersection_3_10', 'intersection_2_9'],
                        ['intersection_1_14', 'dummy', 'intersection_1_13', 'intersection_2_13', 'intersection_1_12'],
                        ['dummy', 'intersection_1_5', 'intersection_2_5', 'intersection_3_5', 'intersection_2_4'],
                        ['intersection_3_9', 'dummy', 'intersection_3_8', 'dummy', 'intersection_3_7'],
                        ['dummy', 'intersection_1_16', 'intersection_2_16', 'intersection_3_16', 'dummy'],
                        ['intersection_3_14', 'dummy', 'intersection_3_13', 'dummy', 'intersection_3_12'],
                        ['intersection_2_7', 'intersection_1_6', 'intersection_2_6', 'intersection_3_6', 'dummy'],
                        ['intersection_3_4', 'dummy', 'intersection_3_3', 'dummy', 'intersection_3_2'],
                        ['intersection_2_12', 'intersection_1_11', 'intersection_2_11', 'intersection_3_11', 'dummy'],
                        ['intersection_2_2', 'intersection_1_1', 'intersection_2_1', 'intersection_3_1', 'dummy']],
    "16_3_ADJACENCY6": [['dummy', 'intersection_1_5', 'intersection_2_5', 'intersection_3_5', 'intersection_2_4'],
                        ['intersection_1_14', 'dummy', 'intersection_1_13', 'intersection_2_13', 'intersection_1_12'],
                        ['dummy', 'intersection_1_16', 'intersection_2_16', 'intersection_3_16', 'dummy'],
                        ['intersection_2_7', 'intersection_1_6', 'intersection_2_6', 'intersection_3_6', 'dummy'],
                        ['intersection_1_4', 'dummy', 'intersection_1_3', 'intersection_2_3', 'intersection_1_2'],
                        ['dummy', 'intersection_1_15', 'intersection_2_15', 'intersection_3_15', 'intersection_2_14'],
                        ['intersection_3_9', 'intersection_2_8', 'intersection_3_8', 'dummy', 'intersection_3_7'],
                        ['dummy', 'intersection_1_10', 'intersection_2_10', 'intersection_3_10', 'intersection_2_9'],
                        ['intersection_3_14', 'dummy', 'intersection_3_13', 'dummy', 'intersection_3_12'],
                        ['intersection_2_2', 'intersection_1_1', 'intersection_2_1', 'intersection_3_1', 'dummy'],
                        ['intersection_1_9', 'dummy', 'intersection_1_8', 'dummy', 'intersection_1_7'],
                        ['intersection_3_4', 'dummy', 'intersection_3_3', 'dummy', 'intersection_3_2'],
                        ['intersection_2_12', 'intersection_1_11', 'intersection_2_11', 'intersection_3_11', 'dummy']],
    # ====== 6x6 (6 rows × 6 cols) ======
    "6_6_ADJACENCY1": [
        ['dummy', 'intersection_1_1', 'intersection_1_2', 'intersection_1_3', 'intersection_2_2'],
        ['intersection_1_4', 'intersection_2_3', 'intersection_2_4', 'intersection_2_5', 'intersection_3_4'],
        ['intersection_2_1', 'dummy', 'intersection_3_1', 'intersection_3_2', 'intersection_4_1'],
        ['intersection_2_6', 'intersection_3_5', 'intersection_3_6', 'dummy', 'intersection_4_6'],
        ['intersection_3_3', 'intersection_4_2', 'intersection_4_3', 'intersection_4_4', 'intersection_5_3'],
        ['intersection_4_5', 'intersection_5_4', 'intersection_5_5', 'intersection_5_6', 'intersection_6_5'],
        ['intersection_5_2', 'intersection_6_1', 'intersection_6_2', 'intersection_6_3', 'dummy'],
        ['dummy', 'dummy', 'intersection_1_5', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_1_6', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_5_1', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_6_4', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_6_6', 'dummy', 'dummy'],
    ],
    # ====== Manhattan 28x7 (7 rows × 28 cols) ======
    "28_7_ADJACENCY1": [
        ['dummy', 'intersection_1_1', 'intersection_1_2', 'intersection_1_3', 'intersection_2_2'],
        ['dummy', 'intersection_1_6', 'intersection_1_7', 'intersection_1_8', 'intersection_2_7'],
        ['dummy', 'intersection_1_11', 'intersection_1_12', 'intersection_1_13', 'intersection_2_12'],
        ['dummy', 'intersection_1_16', 'intersection_1_17', 'intersection_1_18', 'intersection_2_17'],
        ['dummy', 'intersection_1_21', 'intersection_1_22', 'intersection_1_23', 'intersection_2_22'],
        ['dummy', 'intersection_1_26', 'intersection_1_27', 'intersection_1_28', 'intersection_2_27'],
        ['intersection_1_4', 'intersection_2_3', 'intersection_2_4', 'intersection_2_5', 'intersection_3_4'],
        ['intersection_1_9', 'intersection_2_8', 'intersection_2_9', 'intersection_2_10', 'intersection_3_9'],
        ['intersection_1_14', 'intersection_2_13', 'intersection_2_14', 'intersection_2_15', 'intersection_3_14'],
        ['intersection_1_19', 'intersection_2_18', 'intersection_2_19', 'intersection_2_20', 'intersection_3_19'],
        ['intersection_1_24', 'intersection_2_23', 'intersection_2_24', 'intersection_2_25', 'intersection_3_24'],
        ['intersection_2_1', 'dummy', 'intersection_3_1', 'intersection_3_2', 'intersection_4_1'],
        ['intersection_2_6', 'intersection_3_5', 'intersection_3_6', 'intersection_3_7', 'intersection_4_6'],
        ['intersection_2_11', 'intersection_3_10', 'intersection_3_11', 'intersection_3_12', 'intersection_4_11'],
        ['intersection_2_16', 'intersection_3_15', 'intersection_3_16', 'intersection_3_17', 'intersection_4_16'],
        ['intersection_2_21', 'intersection_3_20', 'intersection_3_21', 'intersection_3_22', 'intersection_4_21'],
        ['intersection_2_26', 'intersection_3_25', 'intersection_3_26', 'intersection_3_27', 'intersection_4_26'],
        ['intersection_3_3', 'intersection_4_2', 'intersection_4_3', 'intersection_4_4', 'intersection_5_3'],
        ['intersection_3_8', 'intersection_4_7', 'intersection_4_8', 'intersection_4_9', 'intersection_5_8'],
        ['intersection_3_13', 'intersection_4_12', 'intersection_4_13', 'intersection_4_14', 'intersection_5_13'],
        ['intersection_3_18', 'intersection_4_17', 'intersection_4_18', 'intersection_4_19', 'intersection_5_18'],
        ['intersection_3_23', 'intersection_4_22', 'intersection_4_23', 'intersection_4_24', 'intersection_5_23'],
        ['intersection_3_28', 'intersection_4_27', 'intersection_4_28', 'dummy', 'intersection_5_28'],
        ['intersection_4_5', 'intersection_5_4', 'intersection_5_5', 'intersection_5_6', 'intersection_6_5'],
        ['intersection_4_10', 'intersection_5_9', 'intersection_5_10', 'intersection_5_11', 'intersection_6_10'],
        ['intersection_4_15', 'intersection_5_14', 'intersection_5_15', 'intersection_5_16', 'intersection_6_15'],
        ['intersection_4_20', 'intersection_5_19', 'intersection_5_20', 'intersection_5_21', 'intersection_6_20'],
        ['intersection_4_25', 'intersection_5_24', 'intersection_5_25', 'intersection_5_26', 'intersection_6_25'],
        ['intersection_5_2', 'intersection_6_1', 'intersection_6_2', 'intersection_6_3', 'intersection_7_2'],
        ['intersection_5_7', 'intersection_6_6', 'intersection_6_7', 'intersection_6_8', 'intersection_7_7'],
        ['intersection_5_12', 'intersection_6_11', 'intersection_6_12', 'intersection_6_13', 'intersection_7_12'],
        ['intersection_5_17', 'intersection_6_16', 'intersection_6_17', 'intersection_6_18', 'intersection_7_17'],
        ['intersection_5_22', 'intersection_6_21', 'intersection_6_22', 'intersection_6_23', 'intersection_7_22'],
        ['intersection_5_27', 'intersection_6_26', 'intersection_6_27', 'intersection_6_28', 'intersection_7_27'],
        ['intersection_6_4', 'intersection_7_3', 'intersection_7_4', 'intersection_7_5', 'dummy'],
        ['intersection_6_9', 'intersection_7_8', 'intersection_7_9', 'intersection_7_10', 'dummy'],
        ['intersection_6_14', 'intersection_7_13', 'intersection_7_14', 'intersection_7_15', 'dummy'],
        ['intersection_6_19', 'intersection_7_18', 'intersection_7_19', 'intersection_7_20', 'dummy'],
        ['intersection_6_24', 'intersection_7_23', 'intersection_7_24', 'intersection_7_25', 'dummy'],
        ['dummy', 'dummy', 'intersection_1_5', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_1_10', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_1_15', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_1_20', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_1_25', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_2_28', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_5_1', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_7_1', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_7_6', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_7_11', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_7_16', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_7_21', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_7_26', 'dummy', 'dummy'],
        ['dummy', 'dummy', 'intersection_7_28', 'dummy', 'dummy'],
    ],
}